SELECT
  CAST(employee_id AS BIGINT) AS employee_id
  ,CAST(work_id AS BIGINT) AS work_id
  ,CAST(full_name AS STRING) AS full_name
  ,CAST(display_name AS STRING) AS display_name
  ,CAST(hibob_state AS STRING) AS hibob_state
  ,CAST(email_address AS STRING) AS email_address
  ,CAST(city AS STRING) AS city
  ,CAST(postcode AS STRING) AS postcode
  ,CAST(job_title AS STRING) AS job_title
  ,CAST(department AS STRING) AS department
  ,CAST(team AS STRING) AS team
  ,CAST(sub_team AS STRING) AS sub_team
  ,CAST(team_type AS STRING) AS team_type
  ,CAST(team_site AS STRING) AS team_site
  ,CAST(`site` AS STRING) AS `site`
  ,CAST(country AS STRING) AS country
  ,CAST(manager_name AS STRING) AS manager_name
  ,CAST(manager_employee_id AS STRING) AS manager_employee_id
  ,CAST(manager_work_id AS STRING) AS manager_work_id
  ,CAST(secondlevel_manager_name AS STRING) AS secondlevel_manager_name
  ,CAST(secondlevel_manager_employee_id AS STRING) AS secondlevel_manager_employee_id
  ,CAST(is_manager AS STRING) AS is_manager
  ,CAST(employment_status AS STRING) AS employment_status
  ,CAST(employment_type AS STRING) AS employment_type
  ,CAST(employment_contract AS STRING) AS employment_contract
  ,CAST(fte AS DOUBLE) AS fte
  ,CAST(business_unit AS STRING) AS business_unit
  ,CAST(cost_centre AS STRING) AS cost_centre
  ,CAST(`start_date` AS TIMESTAMP) AS `start_date`
  ,CAST(days_of_previous_service AS BIGINT) AS days_of_previous_service
  ,CAST(role_start_date AS TIMESTAMP) AS role_start_date
  ,CAST(probation_end_date AS DATE) AS probation_end_date
  ,CAST(role_finance_use AS STRING) AS role_finance_use
  ,CAST(discipline AS STRING) AS discipline
  ,CAST(start_date_with_octopus_group AS TIMESTAMP) AS start_date_with_octopus_group
  ,CAST(current_active_status_start_date AS TIMESTAMP) AS current_active_status_start_date
  ,CAST(termination_date AS TIMESTAMP) AS termination_date
  ,CAST(paying_entity AS STRING) AS paying_entity
  ,CAST(report_date AS TIMESTAMP) AS report_date
  ,CAST(_input_filename AS STRING) AS _input_filename
  ,CAST(_ingestion_timestamp AS TIMESTAMP) AS _ingestion_timestamp
FROM {{ source('src_hibob', 'employee_latest') }}
