name: 'elementary_dbt_metadata'
version: '1.0.0'
config-version: 2

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

# These configurations specify where dbt should look for different types of files.
# Anything out of the ordinary should have a comment explaining what it does.
# If a directory is not required for a package it should be removed from the list and the directory should be deleted
model-paths:
  - models
  # Although the groups direcory doesn't contain any models its required for dbt to find the yml file for groups  
  - groups
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

clean-targets:         # directories to be removed by `dbt clean`
  - dbt_packages
  - state
  - target

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  elementary:
    +group: elementary
    +schema: elementary
    +access: private    
  elementary_dbt_metadata:
    +group: elementary
    +schema: elementary
    +access: private
    tags:
      - package:elementary_dbt_metadata

seeds:
  elementary_dbt_metadata:
    tags:
      - package:elementary_dbt_metadata

snapshots:
  elementary_dbt_metadata:
    tags:
      - package:elementary_dbt_metadata

tests:
  elementary_dbt_metadata:
    tags:
      - package:elementary_dbt_metadata  