name: utils_core
version: 1.0.0
config-version: 2
model-paths:
- models
- groups
analysis-paths:
- analyses
test-paths:
- tests
seed-paths:
- seeds
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- dbt_packages
- state
- target
models:
  utils_core:
    +materialized: table
    staging:
      +materialized: view
      +tags:
      - utils_core
      - staging
    macro_tests:
      +materialized: ephemeral
      +access: private
      +tags:
      - utils_core
      - tests
    +group: data_platform
    +access: public
    +tags:
    - utils_core
    - utils
  +persist_docs:
    relation: true
    columns: true
  +tags:
  - utils_core
vars:
  disable_dbt_artifacts_autoupload: "{{ target.name != 'prod' }}"
  disable_dbt_columns_autoupload: "{{ target.name != 'prod' }}"
  disable_run_results: "{{ target.name != 'prod' }}"
  disable_tests_results: "{{ target.name != 'prod' }}"
  disable_dbt_invocation_autoupload: "{{ target.name != 'prod' }}"
  distant_future_timestamp: to_utc_timestamp('2099-12-31 23:59:59','UTC')
  PROD_CATALOG: octoenergy_data_prod_prod
  DATABRICKS_WORKSPACE_ID: '337210421809158'
  local_timezone: UTC
profile: utils_core
