template_version: "1.0.0"
description: "Configuration-driven templates for dbt domain packages"

# Define template variables and their types
variables:
  package_name:
    type: string
    required: true
    description: "Name of the dbt package"
  
  alignment:
    type: choice
    choices: ["source-aligned", "consumer-aligned", "utils"]
    required: true
    description: "Data mesh alignment type"
  domain_name:
    type: string
    required: true
    description: "Domain or use case name"
  
  description:
    type: string
    required: false
    description: "Description of the package"
  
  source_system:
    type: string
    required: false
    required_when: "alignment == 'source-aligned'"
    description: "Source system name for source-aligned packages"
  
  business_area:
    type: string
    required: false
    description: "Business area for consumer-aligned packages"

# Template configurations for different files
templates:
  dbt_project_yml:
    base_config:
      name: "{{ package_name }}"
      version: "1.0.0"
      config-version: 2
      profile: "{{ package_name }}"
      
      # Standard paths
      model-paths: ["models", "groups"]
      analysis-paths: ["analyses"]
      test-paths: ["tests"]
      seed-paths: ["seeds"]
      macro-paths: ["macros"]
      snapshot-paths: ["snapshots"]
      
      clean-targets: ["dbt_packages", "state", "target"]
      
      # Flags for dbt behavior
      flags:
        require_explicit_package_overrides_for_builtin_materializations: false
        use_materialization_v2: true
    
    models:
      base:
        +persist_docs:
          relation: true
          columns: true
        +tags: ["{{ package_name }}"]
      
      source-aligned:
        '{{ package_name }}':
          +group: "{{ group_name }}"
          +materialized: table
          +access: public
          +tags: ["{{ package_name }}", "source-aligned"]
          staging:
            +materialized: view
            +access: private
            +tags: ["{{ package_name }}", "staging"]
      
      consumer-aligned:
        '{{ package_name }}':
          +group: "{{ group_name }}"
          +materialized: table
          +access: public
          +tags: ["{{ package_name }}", "{{ business_area | default('analytics') }}", "consumer-aligned"]
          staging:
            +materialized: view
            +access: private
            +tags: ["{{ package_name }}", "staging"]
          marts:
            +materialized: table
            +access: public
            +tags: ["{{ package_name }}", "marts"]
      
      utils:
        '{{ package_name }}':
          +group: "{{ group_name }}"
          +materialized: table
          +access: public
          +tags: ["{{ package_name }}", "utils"]
          staging:
            +materialized: view
            +tags: ["{{ package_name }}", "staging"]
          macro_tests:
            +materialized: ephemeral
            +tags: ["{{ package_name }}", "tests"]
    
    vars:
      PROD_CATALOG: "octoenergy_data_prod_prod"
      DATABRICKS_WORKSPACE_ID: "337210421809158"
      disable_dbt_artifacts_autoupload: "{{ target.name != 'prod' }}"
      disable_dbt_columns_autoupload: "{{ target.name != 'prod' }}"
      disable_run_results: "{{ target.name != 'prod' }}"
      disable_tests_results: "{{ target.name != 'prod' }}"
      disable_dbt_invocation_autoupload: "{{ target.name != 'prod' }}"
      distant_future_timestamp: "to_utc_timestamp('2099-12-31 23:59:59','UTC')"
      local_timezone: "UTC"

  packages_yml:
    base_packages:
      - package: "dbt-labs/dbt_utils"
        version: ">=1.3.0"
      - package: "dbt-labs/codegen"
        version: ">=0.13.1"
    alignment_specific:
      source-aligned: []
      consumer-aligned: []
      utils: []


  group_yml:
    template: |
      version: 2
      
      groups:
        - name: {{ group_name }}
          owner:
            name: "{{ owner_name | default('Data Platform Team') }}"
            email: "{{ owner_email | default('data-platform@octopusenergy.com') }}"
          description: |
            {{ group_description | default('Data domain for ' + package_name) }}
          config:
            meta:
              team: "{{ team_name | default('data_platform') }}"
              team_description: "{{ team_description | default('Data platform infrastructure and utilities') }}"
              contact: "{{ team_contact }}"
              domains: {{ team_domains | default(['databricks']) | tojson }}

# Directory structure templates
directory_structures:
  source-aligned:
    - "models/staging"
    - "macros"
    - "tests"
    - "groups"
    - "seeds"
    - "snapshots"
    - "analyses"
  
  consumer-aligned:
    - "models/staging"
    - "models/marts"
    - "macros"
    - "tests"
    - "groups"
    - "seeds"
    - "snapshots"
    - "analyses"
  
  utils:
    - "models/staging"
    - "macros"
    - "tests"
    - "groups"
    - "seeds"
    - "snapshots"
    - "analyses"

# Migration configurations for backfilling changes
migrations:
  - version: "1.0.0"
    description: "Add package name tags to all models"
    changes:
      - file: "dbt_project.yml"
        action: "add_tags"
        target: "models.{{ package_name }}"
        values: ["{{ package_name }}"]
  
  - version: "1.1.0"
    description: "Add alignment-specific tags"
    changes:
      - file: "dbt_project.yml"
        action: "add_tags"
        target: "models.{{ package_name }}"
        values: ["{{ alignment }}"]
