template_version: "1.0.0"
description: "Configuration-driven templates for dbt domain packages"

# Define template variables and their types
variables:
  package_name:
    type: string
    required: true
    description: "Name of the dbt package"
  
  alignment:
    type: choice
    choices: ["source-aligned", "consumer-aligned", "utils"]
    required: true
    description: "Data mesh alignment type"
  
  source_system:
    type: string
    required_when: "alignment == 'source-aligned'"
    description: "Source system name for source-aligned domains"
  
  business_area:
    type: string
    required_when: "alignment == 'consumer-aligned'"
    description: "Business area for consumer-aligned domains"
  
  domain_name:
    type: string
    required: true
    description: "Domain or use case name"
  
  description:
    type: string
    required: false
    description: "Description of the package"

# Template configurations for different files
templates:
  dbt_project_yml:
    base_config:
      name: "{{ package_name }}"
      version: "1.0.0"
      config-version: 2
      profile: "{{ package_name }}"
      
      # Standard paths
      model-paths: ["models", "groups"]
      analysis-paths: ["analyses"]
      test-paths: ["tests"]
      seed-paths: ["seeds"]
      macro-paths: ["macros"]
      snapshot-paths: ["snapshots"]
      
      clean-targets: ["dbt_packages", "state", "target"]
    
    models:
      base:
        +persist_docs:
          relation: true
          columns: true
        +tags: ["{{ package_name }}"]
      
      source-aligned:
        '{{ package_name }}':
          +group: "{{ source_system | default('data_platform') }}"
          +schema: "{{ source_system }}"
          +materialized: table
          +access: public
          +tags: ["{{ package_name }}", "source-aligned", "{{ source_system }}"]
          staging:
            +materialized: view
            +access: private
            +tags: ["{{ package_name }}", "staging"]
      
      consumer-aligned:
        '{{ package_name }}':
          +group: "{{ business_area | default('analytics') }}"
          +schema: "{{ business_area }}_{{ domain_name | replace('-', '_') }}"
          +materialized: table
          +access: public
          +tags: ["{{ package_name }}", "consumer-aligned", "{{ business_area }}"]
          staging:
            +materialized: view
            +access: private
            +tags: ["{{ package_name }}", "staging"]
          marts:
            +materialized: table
            +access: public
            +tags: ["{{ package_name }}", "marts"]
      
      utils:
        '{{ package_name }}':
          +group: data_platform
          +materialized: table
          +access: public
          +tags: ["{{ package_name }}", "utils"]
          staging:
            +materialized: view
            +tags: ["{{ package_name }}", "staging"]
          macro_tests:
            +materialized: ephemeral
            +tags: ["{{ package_name }}", "tests"]
    
    vars:
      PROD_CATALOG: "octoenergy_data_prod_prod"
      DATABRICKS_WORKSPACE_ID: "337210421809158"
      disable_dbt_artifacts_autoupload: "{{ target.name != 'prod' }}"
      disable_dbt_columns_autoupload: "{{ target.name != 'prod' }}"
      disable_run_results: "{{ target.name != 'prod' }}"
      disable_tests_results: "{{ target.name != 'prod' }}"
      disable_dbt_invocation_autoupload: "{{ target.name != 'prod' }}"
      distant_future_timestamp: "to_utc_timestamp('2099-12-31 23:59:59','UTC')"
      local_timezone: "UTC"

  packages_yml:
    base_packages:
      - package: "dbt-labs/dbt_utils"
        version: ">=1.3.0"
      - package: "elementary-data/elementary"
        version: ">=0.15.0"
    
    alignment_specific:
      source-aligned:
        - package: "dbt-labs/dbt_external_tables"
          version: ">=0.8.0"
          comment: "For external table management"
      
      consumer-aligned:
        - package: "dbt-labs/metrics"
          version: ">=1.6.0"
          comment: "For analytics and metrics"
      
      utils:
        - package: "dbt-labs/codegen"
          version: ">=0.12.1"
          comment: "For code generation utilities"

  group_yml:
    template: |
      version: 2
      
      groups:
        - name: {{ group_name }}
          owner:
            name: "{{ owner_name | default('Data Platform Team') }}"
            email: "{{ owner_email | default('data-platform@octopusenergy.com') }}"
            description: "{{ group_description }}"

# Directory structure templates
directory_structures:
  source-aligned:
    - "models/staging"
    - "macros"
    - "tests"
    - "groups"
    - "seeds"
    - "snapshots"
    - "analyses"
  
  consumer-aligned:
    - "models/staging"
    - "models/marts"
    - "macros"
    - "tests"
    - "groups"
    - "seeds"
    - "snapshots"
    - "analyses"
  
  utils:
    - "models/staging"
    - "macros"
    - "tests"
    - "groups"
    - "seeds"
    - "snapshots"
    - "analyses"

# Migration configurations for backfilling changes
migrations:
  - version: "1.0.0"
    description: "Add package name tags to all models"
    changes:
      - file: "dbt_project.yml"
        action: "add_tags"
        target: "models.{{ package_name }}"
        values: ["{{ package_name }}"]
  
  - version: "1.1.0"
    description: "Add alignment-specific tags"
    changes:
      - file: "dbt_project.yml"
        action: "add_tags"
        target: "models.{{ package_name }}"
        values: ["{{ alignment }}"]
